# Generated by Django 2.2.1 on 2019-05-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='libri',
            new_name='libro',
        ),
    ]
